# This file is auto generate by tools/config/config_prebuilt.py
# version: from 1602158(Nexus 5) ==> builder.20150924152457_R(Nexus 5)
# Date: 2015/09/24 16:22

BOARD_PREBUILT_DIRS += \
    app/AlarmClock \
    app/AppCenter \
    app/Calendar \
    app/Camera \
    app/ExperienceDataSync \
    app/FileManager \
    app/GameCenter \
    app/IflytekSpeechService \
    app/LogReport \
    app/MzAccount \
    app/MzBackup \
    app/MzBlockService \
    app/MzCloudService \
    app/MzCountService \
    app/MzMPay \
    app/MzSecurity \
    app/MzSetupWizard \
    app/MzSmartComService \
    app/MzSnsSyncService \
    app/MzSyncService \
    app/MzUpdate \
    app/NetContactService \
    app/NotePaper \
    app/O2OService \
    app/Painter \
    app/PicoTts \
    app/Reader \
    app/Search \
    app/SystemWallpaper \
    app/UsageStatsProvider \
    app/WAPPushManager \
    app/Weather \
    app/webview \
    customizecenter \
    framework/flyme-res \
    priv-app/AliAppAccount \
    priv-app/Browser \
    priv-app/Contacts \
    priv-app/CustomizeCenter \
    priv-app/Dialer \
    priv-app/Email \
    priv-app/FlymeLauncher \
    priv-app/Gallery \
    priv-app/Keyguard \
    priv-app/Life \
    priv-app/Mms \
    priv-app/Music \
    priv-app/MzAccountPlugin \
    priv-app/MzInput \
    priv-app/NetworkLocation_baidu \
    priv-app/PowerSaveModeHome \
    priv-app/SoundRecorder \
    priv-app/Tag \
    priv-app/Video \
    priv-app/VoiceAssistant \
    tts \


BOARD_PREBUILT += \
    app/PacProcessor/lib/arm/libjni_pacprocessor.so \
    app/PrintSpooler/lib/arm/libprintspooler_jni.so \
    bin/flymed \
    bin/nmbd \
    bin/pppoe \
    bin/shutdownanimation \
    bin/smbd \
    bin/smbpasswd \
    etc/permissions/com.meizu.camera.xml \
    etc/ppp/init.pppoe-pppd \
    etc/ppp/ip-up-pppoe \
    fonts/AndroidEmoji.ttf \
    fonts/DroidNaskh-Regular.ttf \
    fonts/DroidNaskhUI-Regular.ttf \
    fonts/DroidSansArmenian.ttf \
    fonts/DroidSansGeorgian.ttf \
    fonts/DroidSansHebrew-Bold.ttf \
    fonts/DroidSansHebrew-Regular.ttf \
    fonts/DroidSerif-Bold.ttf \
    fonts/DroidSerif-BoldItalic.ttf \
    fonts/DroidSerif-Italic.ttf \
    fonts/DroidSerif-Regular.ttf \
    fonts/SourceHanSansCN-ExtraLight.ttf \
    fonts/SourceHanSansCN-Normal.ttf \
    fonts/SourceHanSansJP-Normal.ttf \
    fonts/SourceHanSansKR-Normal.ttf \
    framework/com.meizu.camera.jar \
    framework/flyme-framework.jar \
    framework/flyme-telephony-common.jar \
    framework/meizu2_jcifs.jar \
    framework/telephony-meizu.jar \
    lib/libBMapApiEngine_v1_3_5.so \
    lib/libDClient.so \
    lib/libDominantColors.so \
    lib/libFace.so \
    lib/libHAOMA.so \
    lib/libIvw35.so \
    lib/libMzGameCenterLib-jni.so \
    lib/libRSSupport.so \
    lib/libRefocusModule.so \
    lib/libTmsdk-2.0.7-mfr.so \
    lib/libWnnEngDic.so \
    lib/libWnnJpnDic.so \
    lib/libams-1.1.4-64b-mfr.so \
    lib/libaudioinfo_jni.so \
    lib/libbdpush_V1_0.so \
    lib/libblur.so \
    lib/libbspatch.so \
    lib/libdce-1.1.2-mfr.so \
    lib/libdlna_jni.so \
    lib/libeffects_filters.so \
    lib/libeffects_mosaic.so \
    lib/libem_aitalk5.so \
    lib/libentryexpro.so \
    lib/libexif_gallery.so \
    lib/libfile_jni.so \
    lib/libimage_codec.so \
    lib/libimage_dehazing.so \
    lib/libimageproc.so \
    lib/libipc_pref.527.1.so \
    lib/libjni_customizecenter_gauss_blur.so \
    lib/libjni_gallery_utils.so \
    lib/libjni_gauss_blur.so \
    lib/libkanbox_meizu_gallery_sdk.so \
    lib/liblocSDK4d.so \
    lib/liblocSDK_2_5OEM.so \
    lib/libmcode_image.so \
    lib/libmeizucamera.so \
    lib/libmobilesafe360-sdk-jni-524.2.so \
    lib/libnative_blur.so \
    lib/libnetworklocation.so \
    lib/libpatch-1.0.1.so \
    lib/libphoto_process.so \
    lib/libpj_opensl_dev.so \
    lib/libpjsipjni.so \
    lib/librender_engine.so \
    lib/libskia_hw_interface.so \
    lib/libskia_private.so \
    lib/libstlport_shared.so \
    lib/libtaglib.so \
    lib/libttsaisound.so \
    lib/libttscompat.so \
    lib/libttspico.so \
    lib/libttsplusmsc.so \
    lib/libupdate-jni-1.0.1.2002.so \
    lib/libwnndict.so \
    media/audio/alarms/After_school.ogg \
    media/audio/alarms/Beep.ogg \
    media/audio/alarms/Blues.ogg \
    media/audio/alarms/Bon_voyage.ogg \
    media/audio/alarms/Buzzer.ogg \
    media/audio/alarms/Call_of_love.ogg \
    media/audio/alarms/Crow.ogg \
    media/audio/alarms/Crystal.ogg \
    media/audio/alarms/Digital.ogg \
    media/audio/alarms/Dreamland.ogg \
    media/audio/alarms/East_ville_memory.ogg \
    media/audio/alarms/Encounter.ogg \
    media/audio/alarms/Fantasy_city.ogg \
    media/audio/alarms/Guitar.ogg \
    media/audio/alarms/Heartbeat.ogg \
    media/audio/alarms/Home.ogg \
    media/audio/alarms/Life.ogg \
    media/audio/alarms/Machinery_ringtone.ogg \
    media/audio/alarms/Marimba.ogg \
    media/audio/alarms/Mario.ogg \
    media/audio/alarms/Mischief.ogg \
    media/audio/alarms/Morning.ogg \
    media/audio/alarms/Morning_Dew.ogg \
    media/audio/alarms/Morning_run.ogg \
    media/audio/alarms/Music_box.ogg \
    media/audio/alarms/Nighty-night.ogg \
    media/audio/alarms/Passion.ogg \
    media/audio/alarms/Phone_ring.ogg \
    media/audio/alarms/Piano.ogg \
    media/audio/alarms/Progress.ogg \
    media/audio/alarms/Rain_dance.ogg \
    media/audio/alarms/Running_in_the_wind.ogg \
    media/audio/alarms/Simplicity.ogg \
    media/audio/alarms/Soaring.ogg \
    media/audio/alarms/Summer_joys.ogg \
    media/audio/alarms/Technology.ogg \
    media/audio/alarms/That_afternoon.ogg \
    media/audio/alarms/The_World_Cup.ogg \
    media/audio/alarms/The_cantor.ogg \
    media/audio/alarms/The_kittens.ogg \
    media/audio/alarms/The_pitch.ogg \
    media/audio/alarms/Tumbler.ogg \
    media/audio/alarms/Twilight_dance.ogg \
    media/audio/alarms/Wake_up.ogg \
    media/audio/alarms/Waltz.ogg \
    media/audio/notifications/Agile.ogg \
    media/audio/notifications/Arrival.ogg \
    media/audio/notifications/Beating.ogg \
    media/audio/notifications/Blow.ogg \
    media/audio/notifications/Chocolate.ogg \
    media/audio/notifications/Cleverer.ogg \
    media/audio/notifications/Code_Word.ogg \
    media/audio/notifications/Corner.ogg \
    media/audio/notifications/Doorbell.ogg \
    media/audio/notifications/Drop.ogg \
    media/audio/notifications/Empire.ogg \
    media/audio/notifications/Gift.ogg \
    media/audio/notifications/Jump.ogg \
    media/audio/notifications/Laputa.ogg \
    media/audio/notifications/Little_Crystal.ogg \
    media/audio/notifications/Meteor.ogg \
    media/audio/notifications/Naughty.ogg \
    media/audio/notifications/Promotion.ogg \
    media/audio/notifications/Pure.ogg \
    media/audio/notifications/Red_Wine_Cork.ogg \
    media/audio/notifications/Ripples.ogg \
    media/audio/notifications/Shining.ogg \
    media/audio/notifications/Silent_Night.ogg \
    media/audio/notifications/Spining.ogg \
    media/audio/notifications/Tapping.ogg \
    media/audio/notifications/The_North_Star.ogg \
    media/audio/notifications/Triumph.ogg \
    media/audio/notifications/Tunnel.ogg \
    media/audio/notifications/VideoRecord.ogg \
    media/audio/ringtones/After_school.ogg \
    media/audio/ringtones/Beep.ogg \
    media/audio/ringtones/Blues.ogg \
    media/audio/ringtones/Bon_voyage.ogg \
    media/audio/ringtones/Buzzer.ogg \
    media/audio/ringtones/Call_of_love.ogg \
    media/audio/ringtones/Crow.ogg \
    media/audio/ringtones/Crystal.ogg \
    media/audio/ringtones/Digital.ogg \
    media/audio/ringtones/Dreamland.ogg \
    media/audio/ringtones/East_ville_memory.ogg \
    media/audio/ringtones/Encounter.ogg \
    media/audio/ringtones/Fantasy_city.ogg \
    media/audio/ringtones/Guitar.ogg \
    media/audio/ringtones/Heartbeat.ogg \
    media/audio/ringtones/Home.ogg \
    media/audio/ringtones/Life.ogg \
    media/audio/ringtones/Machinery_ringtone.ogg \
    media/audio/ringtones/Marimba.ogg \
    media/audio/ringtones/Mario.ogg \
    media/audio/ringtones/Mischief.ogg \
    media/audio/ringtones/Morning.ogg \
    media/audio/ringtones/Morning_dew.ogg \
    media/audio/ringtones/Morning_run.ogg \
    media/audio/ringtones/Music_box.ogg \
    media/audio/ringtones/Nighty-night.ogg \
    media/audio/ringtones/Passion.ogg \
    media/audio/ringtones/Phone_ring.ogg \
    media/audio/ringtones/Piano.ogg \
    media/audio/ringtones/Progress.ogg \
    media/audio/ringtones/Rain_dance.ogg \
    media/audio/ringtones/Running_in_the_wind.ogg \
    media/audio/ringtones/Simplicity.ogg \
    media/audio/ringtones/Soaring.ogg \
    media/audio/ringtones/Summer_joys.ogg \
    media/audio/ringtones/Technology.ogg \
    media/audio/ringtones/That_afternoon.ogg \
    media/audio/ringtones/The_World_Cup.ogg \
    media/audio/ringtones/The_cantor.ogg \
    media/audio/ringtones/The_kittens.ogg \
    media/audio/ringtones/The_pitch.ogg \
    media/audio/ringtones/Tumbler.ogg \
    media/audio/ringtones/Twilight_dance.ogg \
    media/audio/ringtones/Wake_up.ogg \
    media/audio/ringtones/Waltz.ogg \
    media/audio/ui/boot.ogg \
    media/audio/ui/camera_click_burst.ogg \
    media/audio/ui/charged.ogg \
    media/audio/ui/keyloud.wav \
    media/audio/ui/list_hold_sound.ogg \
    media/audio/ui/msgNotifyIncompose.wav \
    media/audio/ui/plugin.ogg \
    media/audio/ui/recorder_prompt_cn.ogg \
    media/audio/ui/recorder_prompt_en.ogg \
    media/audio/ui/recorder_prompt_end.ogg \
    media/shutanimation.zip \
    priv-app/DefaultContainerService/lib/arm/libdefcontainer_jni.so \


BOARD_PRESIGNED_APPS += \
    AliAppAccount.apk \
    IflytekSpeechService.apk \
    Life.apk \
    MzAccountPlugin.apk \
    NetworkLocation_baidu.apk \
    qcrilmsgtunnel.apk \


 # This is the end.
