BOARD_PREBUILT += \
    lib64/libams-1.1.4-64b-mfr.so \
    lib64/libdce-1.1.2-mfr.so \
    lib64/libdlna_jni.so \
    lib64/libDominantColors.so \
    lib64/libeffects_filters.so \
    lib64/libeffects_mosaic.so \
    lib64/libexif_gallery.so \
    lib64/libFace.so \
    lib64/libHAOMA.so \
    lib64/libimage_codec.so \
    lib64/libimage_dehazing.so \
    lib64/libimageproc.so \
    lib64/libipc_pref.527.1.so \
    lib64/libmcode_image.so \
    lib64/libmobilesafe360-sdk-jni-524.2.so \
    lib64/libnative_blur.so \
    lib64/libpatch-1.0.1.so \
    lib64/libphoto_process.so \
    lib64/libRefocusModule.so \
    lib64/librender_engine.so \
    lib64/libskia_hw_interface.so \
    lib64/libTmsdk-2.0.7-mfr.so \
    lib64/libupdate-jni-1.0.1.2002.so \
    lib64/libaudioinfo_jni.so \
    lib64/libDClient.so \
    lib64/libRefocusModule.so \
    lib64/libblur.so \
    lib64/libmeizucamera.so \
    lib64/libnative_blur.so
